<?php

$q = '';
if (isset($_GET['q'])) {
    $q = strtolower($_GET['q']);
}
if (!$q) {
    return;
}

$items = array(
"Ab roller",
"Arnold press",
"Assisted machine chin ups",
"Assisted machine pull ups",
"Barbell behind the neck press",
"Barbell curls",
"Barbell front raise",
"Barbell good mornings",
"Barbell incline front raise",
"Barbell lunges",
"Barbell military press",
"Barbell preacher curls",
"Barbell rows",
"Barbell shrugs",
"Barbell squat",
"Barbell wrist curls",
"Behind the back pull ups",
"Behind the back wrist curls",
"Bench dips",
"Bench Press",
"Bent over broomstick twists",
"Bent over cable raises",
"Bent over raises",
"Bicycle crunches",
"Cable crossovers",
"Cable crunches",
"Cable curls",
"Cable preacher curls",
"Cable pushdowns",
"Cable reverse curls",
"Calve raises on leg press machine",
"Captain's chair leg raises",
"Chin ups",
"Clean and jerk",
"Close grip bench press",
"Close grip pulldowns",
"Close grip upright rows",
"Concentration curls",
"Crunches",
"Deadlifts",
"Decline barbell press",
"Decline dumbbell fly",
"Decline dumbbell press",
"Donkey calf raises",
"Double crunches",
"Drag curls",
"Dumbbell front raise",
"Dumbbell kickbacks",
"Dumbbell lateral raise",
"Dumbbell lunges",
"Dumbbell preacher curls",
"Dumbbell pullovers",
"Dumbbell shrugs",
"Dumbbell straight legged deadlifts",
"Dumbbell upright rows",
"Flat bench cable crossovers",
"Flat dumbbell bench press",
"Flat dumbbell fly",
"Floor barbell press",
"Floor dumbbell press",
"Front squat",
"Hack squat",
"Hammer curls",
"Hanging leg raises",
"Hanging side crunches",
"Hanging windshield wipers",
"High pull",
"Hyperextensions",
"Incline barbell press",
"Incline crunches",
"Incline dumbbell curls",
"Incline dumbbell fly",
"Incline dumbbell press",
"Incline dumbbell rows",
"Incline sit ups",
"Lat pulldowns",
"Leg extensions",
"Leg press",
"Low cable fly",
"Lying barbell tricep extensions/Skullcrushers",
"Lying dumbbell extension",
"Lying leg curls",
"Lying leg raises",
"Machine crunches",
"Machine curls",
"Machine fly",
"Machine preacher curls",
"Machine press",
"Machine pullovers",
"Machine rows",
"Machine shoulder press",
"Machine shrugs",
"Machine squat",
"One-arm cable reverse grip pushdowns",
"One-arm cable rows",
"One-arm cablee lateral raises",
"One-arm dumbbell rows",
"One-arm dumbbell wrist curls",
"Overhead squats",
"Parallel bar dips",
"Power clean",
"Pull ups",
"Push press",
"Rack pulls",
"Reverse calf raises",
"Reverse crunches",
"Reverse curls",
"Reverse curls",
"Reverse dumbbell wrist curls",
"Reverse grip cable pushdowns",
"Reverse grip pulldowns",
"Reverse preacher curls",
"Reverse wrist curls",
"Romanian deadlifts",
"Rope pulls",
"Seated barbell shoulder press",
"Seated broomstick twists",
"Seated cable rows",
"Seated calf raises",
"Seated dumbbell curls",
"Seated dumbbell shoulder press",
"Seated leg curls",
"Seated overhead barbell extension",
"Seated overhead dumbbell extension",
"Seated wide grip cable rows",
"Side crunches",
"Sit ups",
"Smith machine behind the neck press",
"Smith machine shoulder press",
"Smith machine squat",
"Spider curls",
"Standing calf raises",
"Standing leg curls",
"Straight legged deadlifts",
"T-bar rows",
"Twisting crunches",
"V-ups",
"Weighted Bench dips",
"Weighted chin ups",
"Weighted dips",
"Weighted hyperextentions",
"Weighted pull ups",
"Wide grip upright rows",
"Zercher squats"
);

foreach ($items as $key) {
	if (strpos(strtolower($key), $q) !== false) {
		echo "$key\n";
	}
}
?>