<?php

$q = '';
if (isset($_GET['q'])) {
    $q = strtolower($_GET['q']);
}
if (!$q) {
    return;
}

$items = array(
"Flat Bench Press",
"Bench Press",
"Flat Barbell Bench Press",
"Flat Barbell Press",
"Flat Dumbbell Press",
"Dumbbell Press",
"Incline Press",
"Incline Bench Press",
"Incline Barbell Press",
"Incline Barbell Bench Press",
"Incline Dumbbell Press",
"Flat Dumbbell Fly",
"Flat Cable Fly",
"Incline Dumbbell Fly",
"Incline Cable Fly",
"Seated Cable Fly",
"Standing Cable Fly",
"Pec Dec Fly",
"Flat Cable Crossovers",
"Incline Cable Crossovers",
"Seated Cable Crossovers",
"Standing Cable Crossovers",
"Dumbbell Pullover",
"Dips",
"Weighted Dips",
"Smith Machine Bench Press",
"Smith Machine Incline Bench Press",
"Smith Machine Decline Press",
"Decline Bench Press",
"Decline Barbell Press",
"Decline Barbell Bench Press",
"Decline Dumbbell Press",
"Decline Press",
"Flat Press",
"Incline Press",
"Machine Flat Press",
"Machine Incline Press",
"Machine Wide Grip Press",
"Machine Decline Press",
"Decline Dumbbell Fly",
"Floor Press",
"Floor Dumbbell Press",
"Floor Barbell Press",
"Wide Grip Lat Pulldown",
"Reverse Grip Lat Pulldown",
"Close Grip Lat Pulldown",
"Machine Lat Pulldown",
"Isolateral Lat Pulldown",
"Unilateral Lat Pulldown",
"Pull Ups",
"Weighted Pull Ups",
"Chin Ups",
"Weighted Chin Ups",
"Barbell Row",
"Dumbbell Row",
"One Arm Dumbbell Row",
"Chest Supported Dumbbell Row",
"Machine Row",
"Cable Row",
"High Cable Row",
"Low Cable Row",
"Machine High Row",
"Machine Low Row",
"Rack Deadlifts",
"Deadlifts",
"Dumbbell Pullovers",
"Cable Pullovers",
"Machine Pullovers",
"T-Bar Row",
"Meadow Rows",
"Machine T-Bar Row",
"Assisted Machine Pull Ups",
"Assisted Machine Chin Ups",
"One Arm Barbell Row",
"One Arm Suitcase Row",
"Suitcase Row",
"Rope Pull Ups",
"Rope Chin Ups",
"Machine Isolateral Row",
"Machine Unilateral Row",
"Machine Isolateral Low Row",
"Machine Isolateral High Row",
"Machine Unilateral Low Row",
"Machine Unilateral High Row",
"Overhand Barbell Row",
"Underhand Barbell Row",
"Supinated Barbell Row",
"Pronated Barbell Row",
"Behind The Back Pulldown",
"Smith Machine Barbell Row",
"One Arm Low Cable Row",
"One Arm High Cable Row",
"Dumbbell Shrugs",
"Standing Dumbbell Shugs",
"Seated Dumbbell Shrugs",
"Machine Shrugs",
"Barbell Shrugs",
"Behind The Back Barbell Shrugs",
"Smith Machine Shrugs",
"Wide Grip Upright Row",
"Wide Grip Cable Row",
"Wide Grip Machine Row",
"Barbell Front Raise",
"Dumbbell Front Raise",
"Incline Barbell Front Raise",
"Incline Dumbbell Front Raise",
"Seated Lateral Raise",
"Standing Lateral Raise",
"Machine Lateral Raise",
"Incline Lateral Raise",
"Lying Lateral Raise",
"Barbell Upright Row",
"Dumbell Upright Row",
"Smith Machine Upright Row",
"Seated Dumbbell Press",
"Standing Dumbbell Press",
"Overhead barbell Press",
"Military Press",
"Seated Shoulder Press",
"Seated Overhead Press",
"Seated Military Press",
"Push Press",
"Machine Military Press",
"Machine Shoulder Press",
"Alternating Seated Dumbbell Press",
"Arnold Press",
"Smith Machine Seated Shoulder Press",
"Smith Machine Standing Shoulder Press",
"Reverse Pec Dec Fly",
"Rope Pulls",
"Face Pulls",
"Rope Face Pulls",
"Rear Delt Raise",
"Rear Dumbbell Raise",
"Lying Rear Dumbbell Raise",
"Lying Rear Delt Raise",
"Bent Over Dumbbell Raise",
"Cable Reverse Fly",
"Seated Cable Face Pulls",
"Cuban Press",
"Cable Lateral Raises",
"One Arm Cable Lateral Raises",
"Barbell Curl",
"Seated Dumbbell Curl",
"Standing Dumbbell Curl",
"Alternating Dumbbell Curl",
"Alternating Hammer Curl",
"Hammer Curl",
"Preacher Curl",
"Dumbbell Preacher Curl",
"Spider Curl",
"Drag Curl",
"Preacher Hammer Curl",
"Cable Rope Hammer Curl",
"Cable Curl",
"E-Z Bar Curl",
"Straight Bar Curl",
"Close Grip Barbell Curl",
"Wide Grip Barbell Curl",
"Close Grip Cable Curl",
"Wide Grip Cable Curl",
"Machine Curl",
"Machine Unilateral Curl",
"Machine Isolateral Curl",
"Machine Preacher Curl",
"Machine Hammer Curl",
"Concentration Curl",
"Incline Dumbbell Curl",
"Reverse Curl",
"Overhead Tricep Extension",
"Overhead One Arm Extension",
"Overhead Barbell Extension",
"Overhead Incline Barbell Extension",
"Skullcrushers",
"Lying Dumbbell Extension",
"Lying One Arm Dumbbell Extension",
"Lying Barbell Extension",
"Overhead Dumbbell Extension",
"Cable Overhead Extension",
"French Press",
"Close Grip Bench Press",
"Smith Machine Close Grip Bench Press",
"Close Grip Decline Barbell Press",
"Smith Machine Close Grip Decline Press",
"Weighted Dips",
"Dips",
"Machine Dips",
"Cable Pushdowns",
"Rope Pushdowns",
"Reverse Grip Pushdowns",
"One Arm Cable Pushdowns",
"One Arm Reverse Grip Pushdowns",
"Bench Dips",
"Machine Extensions",
"Tricep Dumbbell Kickabcks",
"Dumbbell Kickbacks",
"Hyperextension",
"Weighted Hyperextension",
"Good Mornings",
"Barbell Squat",
"Machine Squat",
"Smith Machine Dquat",
"Front Squat",
"Leg Press",
"Hack Squat",
"Barbell Lunges",
"Dumbbell Lunges",
"Leg Extensions",
"Piston Squat",
"Bulgarian Squat",
"One Legged Squat",
"Machine Leg Press",
"Vertical Leg Press",
"Reverse Lunges",
"Zercher Squats",
"Overhead Squats",
"Barbell Reverse Lunges",
"Dumbbell Reverse Lunges",
"Lying Leg Curls",
"Seated Leg Curls",
"Standing Leg Curls",
"Straight Legged Deadlifts",
"Romanian Deadlifts",
"Dumbbell Straight Legged Deadlifts",
"Standing One Legged Curls",
"Hamstring Raise",
"Seated Abductors",
"Seated Adductors",
"Standing Calf Raises",
"Seated Calf Press",
"Seated Calf Raises",
"Donkey Calf Raises",
"Reverse Calf Raises",
"One Leg Dumbbell Calf Raises",
"Sumo Deadlift",
"Power Clean",
"Clean and Jerk",
"Clean and Press",
"Snatch",
"High Pull",
"Hang Clean",
"Sit ups",
"Crunches",
"Incline sit ups",
"Incline crunches",
"Side crunches",
"Bicycle crunches",
"Twisting crunches",
"Reverse crunches",
"Hanging leg raises",
"Captain's chair leg raises",
"Machine crunches",
"Cable crunches",
"V-ups",
"Double crunches",
"Seated broomstick twists",
"Bent over broomstick twists",
"Lying leg raises",
"Hanging windshield wipers",
"Hanging side crunches",
"Ab roller",
"Oblique crunches",
"Rope crunches",

);

foreach ($items as $key) {
	if (strpos(strtolower($key), $q) !== false) {
		echo "$key\n";
	}
}
?>