<?php

//$q = '';
//if (isset($_GET['q'])) {
//    $q = strtolower($_GET['q']);
//}
//if (!$q) {
//    return;
//}

$sportlist = array(
	array("Amatuer Bodybuilding",1),
	array("Aquatics",2),
	array("Archery",3),
	array("Archery",4),
	array("Automobile Racing",5),
	array("Badminton",6),
	array("Baseball",7),
	array("Basketball",8),
	array("Biathlon",9),
	array("Biathlon",10),
	array("Bird Watching",11),
	array("Bobsleigh",12),
	array("Bocce Ball",13),
	array("Body Building",14),
	array("Boomerang",15),
	array("Bowling",16),
	array("Boxing",17),
	array("Bull Fighting",18),
	array("Camping",19),
	array("Canoeing",20),
	array("Casual lifting",21),
	array("Caving",22),
	array("Cheerleading",23),
	array("Chess",24),
	array("Classical Dance",25),
	array("Cricket",26),
	array("Crochet",27),
	array("Cross Country Running",28),
	array("Cross Country Skiing",29),
	array("Curling",30),
	array("Cycling",31),
	array("Darts",32),
	array("Decathlon",33),
	array("Diving",34),
	array("Dog Sledding",35),
	array("Dog Training",36),
	array("Down Hill Skiing",37),
	array("Equestrian",38),
	array("Falconry",39),
	array("Fencing",40),
	array("Fencing",41),
	array("Figure Skating",42),
	array("Fishing",43),
	array("Flag Football",44),
	array("Foosball",45),
	array("Football",46),
	array("Fox Hunting",47),
	array("Golf",48),
	array("Gymnastics",49),
	array("Handball",50),
	array("Hang Gliding",51),
	array("High Jump",52),
	array("Hiking",53),
	array("Hockey",54),
	array("Horseback Riding",55),
	array("Horseshoes",56),
	array("Hot Air Ballooning",57),
	array("Hunting",58),
	array("Ice Hockey",59),
	array("Ice Skating",60),
	array("Inline Skating",61),
	array("Jai Alai",62),
	array("Judo",63),
	array("Jump Roping",64),
	array("Karate",65),
	array("Kayaking",66),
	array("Knee Boarding",67),
	array("Lacrosse",68),
	array("Land Sailing",69),
	array("Lifting",70),
	array("Log Rolling",71),
	array("Long Jump",72),
	array("Luge",73),
	array("Medicine Ball",74),
	array("Metal Detecting",75),
	array("Model Flying",76),
	array("Modern Dance",77),
	array("Modern Pentathlon",78),
	array("Motorcycle Racing",79),
	array("Mountain Biking",80),
	array("Mountaineering and Climbing",81),
	array("Netball",82),
	array("Paddle Ball",83),
	array("Paint ball",84),
	array("Para Gliding",85),
	array("Parachuting",86),
	array("Pétanque",87),
	array("Pool Playing",88),
	array("Power Walking",89),
	array("Prospecting",90),
	array("Racket ball",91),
	array("Remote Control Boating",92),
	array("River Rafting",93),
	array("Rock Climbing",94),
	array("Rodeo Riding",95),
	array("Roller Skating",96),
	array("Roller Skating",97),
	array("Rowing",98),
	array("Rowing",99),
	array("Rugby",100),
	array("Sailing",101),
	array("Scuba Diving",102),
	array("Shot Put",103),
	array("Shuffle Board",104),
	array("Skateboarding",105),
	array("Skeet Shooting",106),
	array("Sky Diving",107),
	array("Snooker",108),
	array("Snow Biking",109),
	array("Snow Boarding",110),
	array("Snow Sledding",111),
	array("Snowshoeing",112),
	array("Soccer",113),
	array("Sombo",114),
	array("Speed Skating",115),
	array("Sport Fishing",116),
	array("Sprint Running",117),
	array("Squash",118),
	array("Stunt Plane Flying",119),
	array("Sumo Wrestling",120),
	array("Surfing",121),
	array("Swimming",122),
	array("Synchronized Swimming",123),
	array("Table Tennis",124),
	array("Taekwondo",125),
	array("Tchoukball",126),
	array("Tennis",127),
	array("Track and Field",128),
	array("Train Collecting",129),
	array("Tree Topping",130),
	array("Triathlon",131),
	array("Tug of War",132),
	array("Volleyball",133),
	array("Water Polo",134),
	array("Water Skiing",135),
	array("Water Snorkling",136),
	array("Water Tubing",137),
	array("Weight Lifting",138),
	array("Whale Watching",139),
	array("Wheelchair Basketball",140),
	array("White Water Rafting",141),
	array("Wind Surfing",142),
	array("Wrestling",143),
	array("Wushu",144),
	array("Yachting",145),
	array("Yoga",146)
);

//foreach ($items as $key => $value) {
//	if (strpos(strtolower($key), $q) !== false) {
//		echo"$key\n";
//	}
//}
?>
